"""The tracker as text in the repository, and a tracker rebuilt from it (REQ-0007-TECH-00).

The database is local and gitignored, and with the server in WAL mode a copy of the file holds only what has been
checkpointed - on this repository it was once six days and a whole session behind. So the tracker travels as a dump:
INSERT statements read through SQLite, which sees the WAL, written deterministically so a commit carries a dump diff
only when the tracker changed.

The dump holds rows and schema_version, never schema. The schema lives in lifecycle-schema.sql and migrations.py, and a
dump that carried CREATE statements would be a third definition free to drift from both. Restoring builds the schema
from those two and loads the rows into it.

Each row is exactly one line. A line break inside a value is written as char(10) spliced into the string, so no tool
that normalises whitespace or line endings - this repository's own pre-commit config runs three - can alter tracker
data by tidying the file.
"""

import sqlite3
from pathlib import Path
from typing import Any

# Tables whose rows are the tracker's substance, first, so a reader of the dump meets them before the bookkeeping.
LEADING_TABLES = ("schema_version", "requirements", "tasks", "architecture")

HEADER = (
    "-- Lifecycle tracker data (REQ-0007-TECH-00). Generated by scripts/tracker_dump.py; do not edit by hand.\n"
    "-- Rows only: the schema is lifecycle-schema.sql plus migrations.py.\n"
    "-- Rebuild a tracker from this with: make tracker-restore\n"
)

# Characters a line-oriented tool might rewrite, and how each is written inside a value instead.
_SPLICED = {"\n": "char(10)", "\r": "char(13)"}


def read_only_connection(db_path: str | Path) -> sqlite3.Connection:
    """A connection that sees the WAL and cannot write, even to a database a server has open."""
    return sqlite3.connect(f"{Path(db_path).resolve().as_uri()}?mode=ro", uri=True, timeout=30.0)


def data_tables(connection: sqlite3.Connection) -> list[str]:
    """Every table holding tracker data, found in the database rather than listed by hand.

    A table a future migration adds is exported without anyone remembering to add it here.
    """
    names = [
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]
    leading = [name for name in LEADING_TABLES if name in names]
    return leading + [name for name in names if name not in leading]


def table_columns(connection: sqlite3.Connection, table: str) -> tuple[list[str], list[str]]:
    """The table's columns in schema order, and its primary key columns in key order."""
    info = connection.execute(f'PRAGMA table_info("{table}")').fetchall()
    columns = [row[1] for row in info]
    key = [row[1] for row in sorted(info, key=lambda row: row[5]) if row[5]]
    return columns, key


def sql_literal(value: Any) -> str:
    """A value as SQLite reads it back, on one line."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return str(int(value))
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            raise ValueError(f"{value!r} has no SQL literal")
        return repr(value)
    if isinstance(value, bytes):
        return f"X'{value.hex()}'"
    text = str(value)
    pieces: list[str] = []
    current = ""
    for character in text:
        if character in _SPLICED:
            pieces.append(f"'{current}'" if current else "")
            pieces.append(_SPLICED[character])
            current = ""
        else:
            current += "''" if character == "'" else character
    pieces.append(f"'{current}'" if current or not pieces else "")
    return " || ".join(piece for piece in pieces if piece)


def export_rows(db_path: str | Path) -> str:
    """The tracker's rows as SQL text: deterministic, one row per line, no schema.

    Two exports of an unchanged tracker are byte-identical: rows are in primary-key order, and nothing about the
    export itself - not the time, the host, or the database's path - is written into it.
    """
    path = Path(db_path).resolve()
    if not path.exists():
        raise FileNotFoundError(f"No tracker database at {path}")
    connection = read_only_connection(path)
    lines = [HEADER]
    try:
        # One read transaction, so no table is read either side of another process's write.
        connection.execute("BEGIN")
        for table in data_tables(connection):
            columns, key = table_columns(connection, table)
            order = ", ".join(f'"{column}"' for column in key) or "rowid"
            rows = connection.execute(f'SELECT * FROM "{table}" ORDER BY {order}').fetchall()  # noqa: S608
            lines.append(f"\n-- {table}: {len(rows)} row{'s' if len(rows) != 1 else ''}\n")
            names = ", ".join(f'"{column}"' for column in columns)
            for row in rows:
                values = ", ".join(sql_literal(value) for value in row)
                lines.append(f'INSERT INTO "{table}" ({names}) VALUES ({values});\n')
        connection.execute("COMMIT")
    finally:
        connection.close()
    return "".join(lines)


def write_dump(db_path: str | Path, out_path: str | Path) -> bool:
    """Write the export if it differs from what is there; return whether it changed.

    An unchanged tracker leaves the file untouched - not rewritten with the same bytes - so nothing downstream sees a
    modification that did not happen.
    """
    text = export_rows(db_path)
    destination = Path(out_path)
    if destination.exists() and destination.read_text(encoding="utf-8") == text:
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8", newline="\n")
    return True
