name: Debug Windows Test

on:
  push:
    branches: [ "refactor/*" ]

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[test,dev]" --system
        uv pip install pytest-asyncio pytest-cov pytest-xdist pytest-mock pytest-randomly --system
    
    - name: Check pytest version
      run: |
        python -m pytest --version
        python -c "import sys; print(sys.executable)"
    
    - name: Run simple test
      run: |
        python -m pytest tests/test_database_manager.py -v
    
    - name: Run tests without coverage
      run: |
        python -m pytest tests/ -k "not (property or performance)" -v
    
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -k "not (property or performance)" --cov=src/lifecycle_mcp --cov-report=xml --cov-report=html --cov-report=term --cov-fail-under=50