name: Windows Test

on:
  push:
    branches: [ "refactor/*" ]

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[test,dev]" --system
        uv pip install pytest-asyncio pytest-cov pytest-xdist pytest-mock pytest-randomly --system
    
    - name: Run tests with verbose output
      run: |
        python -m pytest tests/ -v --tb=short -x
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Run tests excluding problematic ones
      if: failure()
      run: |
        python -m pytest tests/ -k "not (property or performance)" -v --tb=short
      env:
        PYTHONIOENCODING: utf-8