name: Windows Minimal Test

on:
  push:
    branches: [ "refactor/*" ]

jobs:
  test-minimal:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install minimal deps
      run: |
        pip install pytest
    
    - name: Run debug test
      run: |
        python -m pytest tests/test_windows_debug.py -v -s