name: Windows Test Final

on:
  push:
    branches: [ "refactor/*" ]

jobs:
  test-windows-final:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies with pip directly
      run: |
        pip install uv
        pip install -e ".[test]"
    
    - name: Test 1 - Simple filter
      run: |
        echo "Test with simple negation"
        python -m pytest tests/ -v --tb=short -m "not slow"
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1
      continue-on-error: true
    
    - name: Test 2 - No filter
      run: |
        echo "Test without any filter"
        python -m pytest tests/test_database_manager.py tests/test_requirement_handler.py -v
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1
      continue-on-error: true
    
    - name: Test 3 - Different quote style
      run: |
        echo "Test with different quotes"
        python -m pytest tests/ -k "not property and not performance" -v --tb=short
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1
      continue-on-error: true
    
    - name: Test 4 - Exclude by deselect
      run: |
        echo "Test with --deselect"
        python -m pytest tests/ --deselect=tests/test_property_based.py --deselect=tests/test_performance_benchmarks.py -v
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1